version: "3.7"

services:
  db:
    image: postgres:13-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: my-weak-password
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pdAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nest.com
      PGADMIN_DEFAULT_PASSWORD: my-weak-password
      PGADMIN_DEFAULT_PORT: 80
    ports:
      - 8080:80
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - db